import os

# Directories
BASE_PATH = os.path.join(os.getcwd(), 'IRIData')
ITEM_SIMILARITIES_DIR = os.path.join(os.getcwd(), 'item_similarities.npy')

CATEGORY_MAPPING = {'CIGARETTES': 1,
                    'SUGAR SUBSTITUTES': 2,
                    'TOOTHPASTE': 3,
                    'DIAPERS': 4,
                    'NUT BUTTER': 5,
                    'FZ PIZZA': 6,
                    'SPAGHETTI/ITALIAN SAUC': 7,
                    'HOUSEHOLD CLEANER': 8,
                    'RAZORS': 9,
                    'FRANKFURTERS': 10,
                    'SHAMPOO': 11,
                    'BEER/ALE/ALCOHOLIC CID': 12,
                    'MILK': 13,
                    'BLADES': 14,
                    'MAYONNAISE': 15,
                    'MUSTARD & KETCHUP': 16,
                    'SOUP': 17,
                    'FZ DINNERS/ENTREES': 18,
                    'TOILET TISSUE': 19,
                    'PHOTOGRAPHY SUPPLIES': 20,
                    'LAUNDRY DETERGENT': 21,
                    'COLD CEREAL': 22,
                    'FACIAL TISSUE': 23,
                    'SALTY SNACKS': 24,
                    'COFFEE': 25,
                    'YOGURT': 26,
                    'TOOTHBRUSH/DENTAL ACCE': 27,
                    'DEODORANT': 28,
                    'CARBONATED BEVERAGES': 29,
                    'MARGARINE/SPREADS': 30,
                    'PAPER TOWELS': 31
                    }

FOODS_DRINK = ['CARBONATED BEVERAGES', 'MAYONNAISE',
               'BEER/ALE/ALCOHOLIC CID', 'SALTY SNACKS', 'FZ PIZZA', 'MILK',
               'SUGAR SUBSTITUTES', 'SPAGHETTI/ITALIAN SAUC', 'BLADES', 'FRANKFURTERS', 'COLD CEREAL',
               'NUT BUTTER', 'YOGURT', 'COFFEE', 'MARGARINE/SPREADS', 'SOUP', 'MUSTARD & KETCHUP', 'FZ DINNERS/ENTREES']

HOUSEHOLDS = ['DIAPERS', 'PAPER TOWELS', 'RAZORS', 'PHOTOGRAPHY SUPPLIES', 'SHAMPOO', 'FACIAL TISSUE',
              'LAUNDRY DETERGENT',
              'DEODORANT', 'TOILET TISSUE', 'CIGARETTES', 'TOOTHBRUSH/DENTAL ACCE', 'HOUSEHOLD CLEANER']

FLAVOR_WORDS = {
    'CLASSIC': ['CLASSC', 'CLASSIQUE', 'CLASSICO', 'CLASSICAL', 'ORIGINAL', 'NATURAL', 'PLAIN', 'REGULAR'],
    'BLEND': ['BLND'],
    'HONEY': ['HONEYED', 'HONEYSUCKLE', 'HONEYCRISP', 'HONY', 'HONEYCOMB'],
    'CHICKEN': ['CHICKN', 'CHCKN', 'CHCK', 'CHICKAPENO', 'CHICKP', 'CHICK', 'CHICKARINA', 'CHICKORY', 'CHKN'],
    'CHERRY': ['CHRRY', 'CHRY', 'CHERRS', 'CHERRIES', 'CHERRYS', 'CHR'],
    'LIME': ['LIMEY', 'LIM', 'LIMEYS', 'LIMEADE', 'LIMONADA', 'LIMEY', 'LIMELIGHT'],
    'LEMON': ['LMN', 'LIMON', 'LEMONADE'],
    'OLIVE': ['OLV', 'OLIVES', 'OLIV'],
    'SPICY': ['SPICE', 'SPICED', 'SPCY'],
    'WATERMELON': ['MELON', 'MELONBALL'],
    'CHEDDAR': ['CHDDR', 'CHDR', 'CHEDDR', 'CHED', 'CHEDR', 'CHWDR'],
    'ONION': ['ONN', 'ONIN'],
    'ORANGE': ['ORNG'],
    'CHOCOLATE': ['CHOC', 'CHCLT', 'CHC', 'CHOCOLAT', 'CHOCO', 'CHOCOLT', 'CHOCLT'],
    'MINT': ['PEPPERMINT', 'MNT', 'POWERMINT', 'BERRYMINT'],
    'PEPPER': ['PPR', 'PPPR', 'PEPPR'],
    'PORK': ['PRK'],
    'FRESH': ['FRSH', 'FRESHNESS', 'FRSHNSS', 'FRESHEST'],
    'STEAK': ['STK'],
    'VANILLA': ['VNLL'],
    'CITRUS': ['CITRON', 'CITRIC', 'CITRS', 'CITRO', 'ORANGESAURUS', 'TANGERINE', 'MANDARIN', 'ORANGEADE', 'CTRS'],
    'CINNAMON': ['CINNMN', 'CINNAMN', 'W/CNMN', 'CNNMN'],
    'MUSHROOM': ['MSHRM'],
    'BBQ': ['BARBECUE', 'BRBQ', 'BARBEQUE'],
    'GARLIC': ['GRLC', 'GARLC', 'GARLC'],
    'VEGETABLE': ['VGTB', 'VEG', 'VGTBL', 'VEGETABLEHERB', 'VEGETAB', 'W/VEG', 'VEGETARIAN', 'VEGERONI', 'VEGETABL'],
    'SHRIMP': ['SHRMP'],
    'BUTTER': ['BTTR', 'BTR', 'BUTTERY'],
    'PARMESAN': ['PRMSN'],
    'MARGARITA': ['MARGHERITA'],
    'HAZELNUT': ['W/HZLNTS', 'HAZELNUTS', 'HZLNT', 'HZN', 'HAZE', 'HAZLNT', 'HAZELNUTS'],
    'MOZZARELLA': ['MOZZRLL', 'MOZZARELL', 'W/MOZZARLL', 'MOZZARLL', 'MZZRLL'],
    'STRAWBERRY': ['STRWBRRY', 'STRW', 'STRWBRY', 'STRAWBERRIS', 'STRAW', 'STRAWBRRY', 'STRAWBRY'],
    'BLUEBERRY': ['BLUEBERRIES', 'BLUESBERRY', 'BLBR', 'BLCKBRRY', 'BLBRY', 'BLBRRY'],
    'RASPBERRY': ['RSPB', 'ASHBERRY', 'RSPBRY', 'RSPBRRY', 'RAZ', 'RASPBRRY'],
    'TOMATO': ['TOMAT', 'TOMT', 'TMT', 'TOM'],
    'CHILI': ['CHL'],
    'RANCH': ['RNCH'],
    'BERRY': ['VERRY', 'PEABERRY', 'BRRY', 'BERRIES', 'HOLLYBERRY', 'WILDBERRY', 'BLACKBERRY', 'MARIONBERRY',
              'BOYSENBERRY'],
    'BEEF': ['BEF', 'BEE', 'BEEFSTOCK', 'BEEFY', 'BEEFSTEAK'],
    'ALMOND': ['ALMND'],
    'COLOMBIAN': ['COLOMBIN', 'CLMBN', 'COLOMBIA'],
    'FRUIT': ['FRT'],
    'GINGER': ['GINGERBREAD', 'GNGR'],
    'BACON': ['BCN'],
    'GREEN': ['GRN'],
    'CRUNCH': ['CRNCH'],
    'ALFREDO': ['ALFRD'],
    'WHEAT': ['WHT'],
    'FRENCH': ['FRNCH'],
    'BREAKFAST': ['BRKFST'],
    'CAFE': ['CAFFE'],
    'CREAM': ['CRMY', 'CREM', 'CREAMY', 'CRM'],
    'GRILlED': ['GRILED', 'GRL', 'GRLD', 'GRILlED'],
    'MORNING': ['MNG'],
    'SWEET': ['SWET', 'SWT'],
    'GUATEMALA': ['GUATEMALAN'],
    'MIXED': ['MIX'],
    'ROAST': ['ROASTED', 'ROASTD', 'ROSTD', 'RSTD', 'RST'],
    'BEAN': ['BEANS'],
    'BREAST': ['BRST'],
    'CHEESE': ['CHEESY', 'CHES', 'CHESBRGR', 'CHEES'],
    'ICED': ['ICE', 'ICY'],
    'BLACK': ['BLCK'],
    'ARTICHOKE': ['ARTCHK'],
    'PINA COLADA': ['PINA']
}

SKIP_WORDS = ['AND', 'CHS', 'STR', 'VNL', 'CRN', 'PST',
              'STYL', 'STYLE', 'CRML', 'RAIN', 'EXTRA', 'THE', 'PCN',
              '100%', 'WITH', 'ITLN', 'VERY', 'SUPER', 'NOT', 'PCH', 'HRB', 'JACK', 'ISLAND', 'JCK', 'BLUE', 'RED',
              'FRSH', 'FRESHNESS', 'FRSHNSS', 'FRESHEST', 'FRESH', 'COOL', 'SMOOTH', 'BREEZE',
              'WILD', 'SPLIT', 'NDL', 'WLD', 'CON', 'ULTIMATE', 'BROWN', 'ALL', 'AFTER', 'SLT', 'COLADA']

FULL_WORDS = ['ULTRA LIGHT', 'UNSCENTED', 'NOT PERFUMED', 'NOT STATED ON PACKGE', 'FULL FLAVOR', 'ROOT BEER',
              'FRENCH ROAST']
